import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Trash2, Plus } from "lucide-react";
import { useAddJobOrder } from "@/integrations/supabase/hooks/useJobOrders";

interface LineItem {
  description: string;
  quantity: number;
  unit_price: number;
  markup: number;
  total: number;
}

interface CreateJobOrderDialogProps {
  isOpen: boolean;
  onClose: () => void;
  projectId: string;
  projectName: string;
  customerId: string;
  customerName: string;
}

export function CreateJobOrderDialog({
  isOpen,
  onClose,
  projectId,
  projectName,
  customerId,
  customerName,
}: CreateJobOrderDialogProps) {
  const addJobOrder = useAddJobOrder();
  
  const [status, setStatus] = useState<"active" | "in-progress" | "completed" | "on-hold">("active");
  const [taxRate, setTaxRate] = useState(8.25);
  const [startDate, setStartDate] = useState(new Date().toISOString().split("T")[0]);
  const [completionDate, setCompletionDate] = useState("");
  const [lineItems, setLineItems] = useState<LineItem[]>([
    { description: "", quantity: 1, unit_price: 0, markup: 30, total: 0 },
  ]);

  const calculateLineItemTotal = (quantity: number, unitPrice: number, markup: number): number => {
    const markedUpPrice = unitPrice / (1 - markup / 100);
    return quantity * markedUpPrice;
  };

  const updateLineItem = (index: number, field: keyof LineItem, value: string | number) => {
    const updated = [...lineItems];
    updated[index] = { ...updated[index], [field]: value };
    
    if (field === "quantity" || field === "unit_price" || field === "markup") {
      const qty = field === "quantity" ? Number(value) : updated[index].quantity;
      const price = field === "unit_price" ? Number(value) : updated[index].unit_price;
      const mrk = field === "markup" ? Number(value) : updated[index].markup;
      updated[index].total = calculateLineItemTotal(qty, price, mrk);
    }
    
    setLineItems(updated);
  };

  const addLineItem = () => {
    setLineItems([...lineItems, { description: "", quantity: 1, unit_price: 0, markup: 30, total: 0 }]);
  };

  const removeLineItem = (index: number) => {
    if (lineItems.length > 1) {
      setLineItems(lineItems.filter((_, i) => i !== index));
    }
  };

  const subtotal = lineItems.reduce((sum, item) => sum + item.total, 0);
  const taxAmount = subtotal * (taxRate / 100);
  const total = subtotal + taxAmount;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    const validLineItems = lineItems.filter(item => item.description.trim() !== "");
    if (validLineItems.length === 0) return;

    await addJobOrder.mutateAsync({
      jobOrder: {
        number: "", // Auto-generated by database trigger
        estimate_id: null,
        customer_id: customerId,
        customer_name: customerName,
        project_id: projectId,
        project_name: projectName,
        status,
        subtotal,
        tax_rate: taxRate,
        tax_amount: taxAmount,
        total,
        invoiced_amount: 0,
        remaining_amount: total,
        start_date: startDate,
        completion_date: completionDate || undefined,
      },
      lineItems: validLineItems.map(item => ({
        description: item.description,
        quantity: item.quantity,
        unit_price: item.unit_price,
        markup: item.markup,
        total: item.total,
      })),
    });

    onClose();
    resetForm();
  };

  const resetForm = () => {
    setStatus("active");
    setTaxRate(8.25);
    setStartDate(new Date().toISOString().split("T")[0]);
    setCompletionDate("");
    setLineItems([{ description: "", quantity: 1, unit_price: 0, markup: 30, total: 0 }]);
  };

  const handleClose = () => {
    onClose();
    resetForm();
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className="bg-card border-border max-w-3xl max-h-[90vh] flex flex-col p-0 overflow-hidden">
        <DialogHeader className="px-6 pt-6 pb-4 flex-shrink-0">
          <DialogTitle className="font-heading">Create Job Order</DialogTitle>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto px-6">
          <form id="create-jo-form" onSubmit={handleSubmit} className="space-y-6 pb-6">
            {/* Project & Customer Info (Read-only) */}
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label className="text-muted-foreground">Project</Label>
                <div className="p-3 bg-muted/50 rounded-md text-sm">{projectName}</div>
              </div>
              <div className="space-y-2">
                <Label className="text-muted-foreground">Customer</Label>
                <div className="p-3 bg-muted/50 rounded-md text-sm">{customerName}</div>
              </div>
            </div>

            {/* Status & Dates */}
            <div className="grid grid-cols-3 gap-4">
              <div className="space-y-2">
                <Label>Status</Label>
                <Select value={status} onValueChange={(v) => setStatus(v as typeof status)}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="active">Active</SelectItem>
                    <SelectItem value="in-progress">In Progress</SelectItem>
                    <SelectItem value="on-hold">On Hold</SelectItem>
                    <SelectItem value="completed">Completed</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>Start Date</Label>
                <Input
                  type="date"
                  value={startDate}
                  onChange={(e) => setStartDate(e.target.value)}
                  required
                />
              </div>
              <div className="space-y-2">
                <Label>Completion Date</Label>
                <Input
                  type="date"
                  value={completionDate}
                  onChange={(e) => setCompletionDate(e.target.value)}
                />
              </div>
            </div>

            {/* Tax Rate */}
            <div className="w-32 space-y-2">
              <Label>Tax Rate (%)</Label>
              <Input
                type="number"
                step="0.01"
                value={taxRate}
                onChange={(e) => setTaxRate(Number(e.target.value))}
              />
            </div>

            {/* Line Items */}
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <Label className="text-base font-semibold">Line Items</Label>
                <Button type="button" variant="outline" size="sm" onClick={addLineItem}>
                  <Plus className="h-4 w-4 mr-1" />
                  Add Item
                </Button>
              </div>

              <div className="space-y-3">
                {lineItems.map((item, index) => (
                  <div key={index} className="grid grid-cols-12 gap-2 items-end p-3 bg-muted/30 rounded-lg">
                    <div className="col-span-4 space-y-1">
                      <Label className="text-xs text-muted-foreground">Description</Label>
                      <Input
                        value={item.description}
                        onChange={(e) => updateLineItem(index, "description", e.target.value)}
                        placeholder="Description"
                      />
                    </div>
                    <div className="col-span-2 space-y-1">
                      <Label className="text-xs text-muted-foreground">Qty</Label>
                      <Input
                        type="number"
                        value={item.quantity}
                        onChange={(e) => updateLineItem(index, "quantity", e.target.value)}
                        min="1"
                      />
                    </div>
                    <div className="col-span-2 space-y-1">
                      <Label className="text-xs text-muted-foreground">Unit Price</Label>
                      <div className="relative">
                        <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">$</span>
                        <Input
                          type="number"
                          step="0.01"
                          value={item.unit_price}
                          onChange={(e) => updateLineItem(index, "unit_price", e.target.value)}
                          className="pl-7"
                        />
                      </div>
                    </div>
                    <div className="col-span-2 space-y-1">
                      <Label className="text-xs text-muted-foreground">Margin %</Label>
                      <Input
                        type="number"
                        step="0.01"
                        value={item.markup}
                        onChange={(e) => updateLineItem(index, "markup", e.target.value)}
                        max="99"
                      />
                    </div>
                    <div className="col-span-1 space-y-1">
                      <Label className="text-xs text-muted-foreground">Total</Label>
                      <div className="p-2 text-sm font-medium">${item.total.toFixed(2)}</div>
                    </div>
                    <div className="col-span-1 flex justify-end">
                      <Button
                        type="button"
                        variant="ghost"
                        size="icon"
                        onClick={() => removeLineItem(index)}
                        disabled={lineItems.length === 1}
                      >
                        <Trash2 className="h-4 w-4 text-destructive" />
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Totals */}
            <div className="flex justify-end">
              <div className="w-64 space-y-2 text-sm">
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Subtotal:</span>
                  <span>${subtotal.toFixed(2)}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Tax ({taxRate}%):</span>
                  <span>${taxAmount.toFixed(2)}</span>
                </div>
                <div className="flex justify-between font-semibold text-base pt-2 border-t">
                  <span>Total:</span>
                  <span>${total.toFixed(2)}</span>
                </div>
              </div>
            </div>
          </form>
        </div>

        <div className="flex justify-end gap-3 px-6 py-4 border-t border-border flex-shrink-0">
          <Button type="button" variant="outline" onClick={handleClose}>
            Cancel
          </Button>
          <Button type="submit" form="create-jo-form" disabled={addJobOrder.isPending}>
            {addJobOrder.isPending ? "Creating..." : "Create Job Order"}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
