import { useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "@/components/ui/command";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Loader2, Truck, DollarSign, TrendingUp, Check, ChevronsUpDown } from "lucide-react";
import { cn } from "@/lib/utils";
import { useVendors } from "@/integrations/supabase/hooks/useVendors";
import { useJobOrders } from "@/integrations/supabase/hooks/useJobOrders";
import { useAddPurchaseOrder } from "@/integrations/supabase/hooks/usePurchaseOrders";
import { ChangeOrderWithLineItems } from "@/integrations/supabase/hooks/useChangeOrders";
import { formatCurrency } from "@/lib/utils";

interface ConvertCOToPODialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  changeOrder: ChangeOrderWithLineItems;
}

export function ConvertCOToPODialog({
  open,
  onOpenChange,
  changeOrder,
}: ConvertCOToPODialogProps) {
  const navigate = useNavigate();
  const [selectedVendor, setSelectedVendor] = useState(changeOrder.vendor_id || "");
  const [vendorComboboxOpen, setVendorComboboxOpen] = useState(false);
  const [vendorSearch, setVendorSearch] = useState("");
  const [dueDate, setDueDate] = useState(() => {
    const date = new Date();
    date.setDate(date.getDate() + 30);
    return date.toISOString().split("T")[0];
  });

  const { data: vendors, isLoading: loadingVendors } = useVendors();
  const { data: jobOrders } = useJobOrders();
  const addPurchaseOrder = useAddPurchaseOrder();

  const selectedVendorData = vendors?.find((v) => v.id === selectedVendor);

  const filteredVendors = vendors?.filter(vendor =>
    vendor.name.toLowerCase().includes(vendorSearch.toLowerCase()) ||
    vendor.specialty?.toLowerCase().includes(vendorSearch.toLowerCase())
  ) || [];

  // Find job order for this project
  const projectJobOrder = jobOrders?.find(
    (jo) => jo.project_id === changeOrder.project_id
  );

  // Calculate totals using vendor costs
  const vendorSubtotal = changeOrder.line_items.reduce(
    (sum, item) => sum + item.quantity * (item.vendor_cost || 0),
    0
  );
  const clientTotal = changeOrder.total;
  const grossProfit = clientTotal - vendorSubtotal;
  const marginPercent = vendorSubtotal > 0 ? ((grossProfit / vendorSubtotal) * 100) : 0;

  const handleConvert = async () => {
    if (!selectedVendor || !projectJobOrder) return;

    const lineItems = changeOrder.line_items.map((item) => ({
      description: item.description,
      quantity: item.quantity,
      unit_price: item.vendor_cost || 0, // Use vendor cost as PO unit price
      markup: 0,
      total: item.quantity * (item.vendor_cost || 0),
    }));

    const subtotal = lineItems.reduce((sum, item) => sum + item.total, 0);

    await addPurchaseOrder.mutateAsync({
      purchaseOrder: {
        number: "", // Auto-generated by database
        job_order_id: projectJobOrder.id,
        job_order_number: projectJobOrder.number,
        vendor_id: selectedVendor,
        vendor_name: selectedVendorData?.name || "",
        project_id: changeOrder.project_id,
        project_name: changeOrder.project?.name || "",
        customer_id: changeOrder.customer_id,
        customer_name: changeOrder.customer_name,
        status: "draft",
        subtotal,
        tax_rate: 0,
        tax_amount: 0,
        total: subtotal,
        due_date: dueDate,
        notes: `Created from Change Order ${changeOrder.number}: ${changeOrder.reason}`,
      },
      lineItems,
    });

    onOpenChange(false);
    navigate(`/projects/${changeOrder.project_id}`);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Truck className="h-5 w-5 text-primary" />
            Convert to Purchase Order
          </DialogTitle>
          <DialogDescription>
            Create a new Purchase Order from {changeOrder.number} using vendor costs.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* Vendor Selection */}
          <div className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <Label>Select Vendor *</Label>
              {loadingVendors ? (
                <div className="flex items-center gap-2 text-muted-foreground">
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Loading...
                </div>
              ) : (
                <Popover open={vendorComboboxOpen} onOpenChange={setVendorComboboxOpen}>
                  <PopoverTrigger asChild>
                    <Button
                      variant="outline"
                      role="combobox"
                      aria-expanded={vendorComboboxOpen}
                      className={cn(
                        "w-full justify-between",
                        !selectedVendor && "text-muted-foreground"
                      )}
                    >
                      {selectedVendorData ? (
                        <div className="flex flex-col items-start text-left">
                          <span className="font-medium">{selectedVendorData.name}</span>
                          {selectedVendorData.specialty && (
                            <span className="text-xs text-muted-foreground">
                              {selectedVendorData.specialty}
                            </span>
                          )}
                        </div>
                      ) : (
                        "Search vendors..."
                      )}
                      <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-[400px] p-0" align="start">
                    <Command>
                      <CommandInput
                        placeholder="Search vendors..."
                        value={vendorSearch}
                        onValueChange={setVendorSearch}
                      />
                      <CommandList>
                        <CommandEmpty>No vendors found.</CommandEmpty>
                        <CommandGroup>
                          {filteredVendors.map((vendor) => (
                            <CommandItem
                              key={vendor.id}
                              value={`${vendor.name} ${vendor.specialty || ''}`}
                              onSelect={() => {
                                setSelectedVendor(vendor.id);
                                setVendorComboboxOpen(false);
                                setVendorSearch("");
                              }}
                            >
                              <Check
                                className={cn(
                                  "mr-2 h-4 w-4",
                                  selectedVendor === vendor.id ? "opacity-100" : "opacity-0"
                                )}
                              />
                              <div className="flex flex-col">
                                <span className="font-medium">{vendor.name}</span>
                                {vendor.specialty && (
                                  <span className="text-xs text-muted-foreground">
                                    {vendor.specialty}
                                  </span>
                                )}
                              </div>
                            </CommandItem>
                          ))}
                        </CommandGroup>
                      </CommandList>
                    </Command>
                  </PopoverContent>
                </Popover>
              )}
            </div>

            <div className="space-y-2">
              <Label>Due Date</Label>
              <Input
                type="date"
                value={dueDate}
                onChange={(e) => setDueDate(e.target.value)}
              />
            </div>
          </div>

          {/* Financial Summary */}
          <div className="p-4 rounded-lg border border-border bg-secondary/20 space-y-3">
            <p className="text-sm font-medium flex items-center gap-2">
              <TrendingUp className="h-4 w-4" />
              Financial Summary
            </p>
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <p className="text-muted-foreground">Client Total</p>
                <p className="font-semibold text-lg">{formatCurrency(clientTotal)}</p>
              </div>
              <div>
                <p className="text-muted-foreground">Vendor Cost Total</p>
                <p className="font-semibold text-lg">{formatCurrency(vendorSubtotal)}</p>
              </div>
              <div className="col-span-2 pt-2 border-t border-border">
                <p className="text-muted-foreground">Gross Profit</p>
                <p className="font-semibold text-lg text-green-600">
                  {formatCurrency(grossProfit)} ({marginPercent.toFixed(1)}% margin)
                </p>
              </div>
            </div>
          </div>

          {/* Line Items Preview */}
          <div className="space-y-2">
            <Label>Line Items (using Vendor Costs)</Label>
            <div className="border rounded-lg overflow-hidden">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Description</TableHead>
                    <TableHead className="text-right">Qty</TableHead>
                    <TableHead className="text-right">Client Price</TableHead>
                    <TableHead className="text-right">Vendor Cost</TableHead>
                    <TableHead className="text-right">PO Total</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {changeOrder.line_items.map((item) => (
                    <TableRow key={item.id}>
                      <TableCell className="font-medium">{item.description}</TableCell>
                      <TableCell className="text-right">{item.quantity}</TableCell>
                      <TableCell className="text-right text-muted-foreground">
                        {formatCurrency(item.unit_price)}
                      </TableCell>
                      <TableCell className="text-right">
                        {formatCurrency(item.vendor_cost || 0)}
                      </TableCell>
                      <TableCell className="text-right font-medium">
                        {formatCurrency(item.quantity * (item.vendor_cost || 0))}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          </div>

          {!projectJobOrder && (
            <div className="p-3 rounded-lg bg-destructive/10 text-destructive text-sm">
              No Job Order found for this project. Please create a Job Order first.
            </div>
          )}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button
            onClick={handleConvert}
            disabled={!selectedVendor || !projectJobOrder || addPurchaseOrder.isPending}
          >
            {addPurchaseOrder.isPending && (
              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
            )}
            <DollarSign className="h-4 w-4 mr-2" />
            Create Purchase Order
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
