import { FormTheme } from "@/integrations/supabase/hooks/useApplicationFormTemplates";

export interface PresetTheme {
  id: string;
  name: string;
  thumbnail: string;
  theme: FormTheme;
}

export const PRESET_THEMES: PresetTheme[] = [
  {
    id: "default",
    name: "Default",
    thumbnail: "linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%)",
      theme: {
        layout: "card",
        backgroundColor: "#f8fafc",
        backgroundGradient: undefined,
        backgroundImage: undefined,
        fontFamily: "inherit",
        buttonColor: "#0f172a",
        buttonText: "Submit Application",
        buttonTextColor: "#ffffff",
      },
  },
  {
    id: "nebula",
    name: "Nebula",
    thumbnail: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
    theme: {
      layout: "card",
      backgroundColor: "#1a1a2e",
      backgroundGradient: "linear-gradient(135deg, #1a1a2e 0%, #16213e 30%, #0f3460 60%, #533483 100%)",
      backgroundImage: undefined,
      fontFamily: "'Poppins', sans-serif",
      buttonColor: "#e94560",
      buttonText: "Submit Application",
      buttonTextColor: "#ffffff",
    },
  },
  {
    id: "nightfall",
    name: "Nightfall",
    thumbnail: "linear-gradient(180deg, #0c0c1e 0%, #1a1a3e 50%, #2d2d5a 100%)",
    theme: {
      layout: "card",
      backgroundColor: "#0c0c1e",
      backgroundGradient: "linear-gradient(180deg, #0c0c1e 0%, #1a1a3e 40%, #2d2d5a 70%, #4a4a8a 100%)",
      backgroundImage: undefined,
      fontFamily: "'Montserrat', sans-serif",
      buttonColor: "#8b5cf6",
      buttonText: "Submit Application",
      buttonTextColor: "#ffffff",
    },
  },
  {
    id: "ocean-blue",
    name: "Ocean Blue",
    thumbnail: "linear-gradient(180deg, #0077b6 0%, #00b4d8 50%, #90e0ef 100%)",
    theme: {
      layout: "card",
      backgroundColor: "#0077b6",
      backgroundGradient: "linear-gradient(180deg, #03045e 0%, #0077b6 40%, #00b4d8 70%, #90e0ef 100%)",
      backgroundImage: undefined,
      fontFamily: "'Open Sans', sans-serif",
      buttonColor: "#03045e",
      buttonText: "Submit Application",
      buttonTextColor: "#ffffff",
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    thumbnail: "linear-gradient(135deg, #ff6b35 0%, #f7c59f 50%, #2ec4b6 100%)",
    theme: {
      layout: "card",
      backgroundColor: "#ff6b35",
      backgroundGradient: "linear-gradient(135deg, #1a1a2e 0%, #ff6b35 30%, #f7931a 60%, #ffd166 100%)",
      backgroundImage: undefined,
      fontFamily: "'Lato', sans-serif",
      buttonColor: "#ff6b35",
      buttonText: "Submit Application",
      buttonTextColor: "#ffffff",
    },
  },
  {
    id: "forest",
    name: "Forest",
    thumbnail: "linear-gradient(180deg, #1b4332 0%, #2d6a4f 50%, #40916c 100%)",
    theme: {
      layout: "card",
      backgroundColor: "#1b4332",
      backgroundGradient: "linear-gradient(180deg, #081c15 0%, #1b4332 30%, #2d6a4f 60%, #40916c 100%)",
      backgroundImage: undefined,
      fontFamily: "'Source Sans Pro', sans-serif",
      buttonColor: "#52b788",
      buttonText: "Submit Application",
      buttonTextColor: "#1b4332",
    },
  },
  {
    id: "minimalist",
    name: "Minimalist",
    thumbnail: "linear-gradient(180deg, #ffffff 0%, #f5f5f5 100%)",
    theme: {
      layout: "fullwidth",
      backgroundColor: "#ffffff",
      backgroundGradient: undefined,
      backgroundImage: undefined,
      fontFamily: "'Inter', sans-serif",
      buttonColor: "#171717",
      buttonText: "Submit",
      buttonTextColor: "#ffffff",
    },
  },
  {
    id: "corporate",
    name: "Corporate",
    thumbnail: "linear-gradient(135deg, #1e3a5f 0%, #2c5282 50%, #3182ce 100%)",
    theme: {
      layout: "card",
      backgroundColor: "#1e3a5f",
      backgroundGradient: "linear-gradient(135deg, #1a365d 0%, #2c5282 50%, #3182ce 100%)",
      backgroundImage: undefined,
      fontFamily: "'Roboto', sans-serif",
      buttonColor: "#2b6cb0",
      buttonText: "Submit Application",
      buttonTextColor: "#ffffff",
    },
  },
  {
    id: "construction",
    name: "Construction",
    thumbnail: "linear-gradient(135deg, #1a1a1a 0%, #333333 50%, #f59e0b 100%)",
    theme: {
      layout: "card",
      backgroundColor: "#1a1a1a",
      backgroundGradient: "linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 40%, #2d2d2d 70%, #404040 100%)",
      backgroundImage: undefined,
      fontFamily: "'Montserrat', sans-serif",
      buttonColor: "#f59e0b",
      buttonText: "Submit Application",
      buttonTextColor: "#000000",
    },
  },
  {
    id: "tech-modern",
    name: "Tech Modern",
    thumbnail: "linear-gradient(135deg, #0f0f23 0%, #1a1a40 50%, #3b82f6 100%)",
    theme: {
      layout: "card",
      backgroundColor: "#0f0f23",
      backgroundGradient: "linear-gradient(135deg, #0f0f23 0%, #1a1a40 30%, #252566 60%, #3b3b99 100%)",
      backgroundImage: undefined,
      fontFamily: "'Inter', sans-serif",
      buttonColor: "#3b82f6",
      buttonText: "Submit Application",
      buttonTextColor: "#ffffff",
    },
  },
  {
    id: "warm-earth",
    name: "Warm Earth",
    thumbnail: "linear-gradient(180deg, #78350f 0%, #a16207 50%, #d97706 100%)",
    theme: {
      layout: "card",
      backgroundColor: "#78350f",
      backgroundGradient: "linear-gradient(180deg, #451a03 0%, #78350f 30%, #a16207 60%, #d97706 100%)",
      backgroundImage: undefined,
      fontFamily: "'Lato', sans-serif",
      buttonColor: "#f59e0b",
      buttonText: "Submit Application",
      buttonTextColor: "#451a03",
    },
  },
  {
    id: "arctic",
    name: "Arctic",
    thumbnail: "linear-gradient(180deg, #0c4a6e 0%, #0ea5e9 50%, #e0f2fe 100%)",
    theme: {
      layout: "card",
      backgroundColor: "#0c4a6e",
      backgroundGradient: "linear-gradient(180deg, #082f49 0%, #0c4a6e 30%, #0284c7 60%, #38bdf8 100%)",
      backgroundImage: undefined,
      fontFamily: "'Open Sans', sans-serif",
      buttonColor: "#0ea5e9",
      buttonText: "Submit Application",
      buttonTextColor: "#ffffff",
    },
  },
];
