import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useAddPersonnel } from "@/integrations/supabase/hooks/usePersonnel";
import { useBulkAssignPersonnelToProject } from "@/integrations/supabase/hooks/usePersonnelProjectAssignments";
import { toast } from "sonner";
import { UserPlus, Check } from "lucide-react";

interface QuickAddPersonnelDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  projectId?: string;
  projectName?: string;
  onSuccess?: () => void;
}

export function QuickAddPersonnelDialog({ 
  open, 
  onOpenChange, 
  projectId,
  projectName,
  onSuccess 
}: QuickAddPersonnelDialogProps) {
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [hourlyRate, setHourlyRate] = useState("");
  const [status, setStatus] = useState<"active" | "inactive">("active");
  const [autoAssign, setAutoAssign] = useState(true);

  const addPersonnel = useAddPersonnel();
  const assignToProject = useBulkAssignPersonnelToProject();

  const resetForm = () => {
    setFirstName("");
    setLastName("");
    setEmail("");
    setPhone("");
    setHourlyRate("");
    setStatus("active");
    setAutoAssign(true);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!firstName.trim() || !lastName.trim() || !email.trim()) {
      toast.error("Please fill in all required fields");
      return;
    }

    const rate = parseFloat(hourlyRate);
    if (isNaN(rate) || rate < 0) {
      toast.error("Please enter a valid hourly rate");
      return;
    }

    try {
      const result = await addPersonnel.mutateAsync({
        first_name: firstName.trim(),
        last_name: lastName.trim(),
        email: email.trim(),
        phone: phone.trim() || null,
        hourly_rate: rate,
        status,
        personnel_number: "", // Auto-generated by trigger
      });

      // Auto-assign to project if selected
      if (autoAssign && projectId && result?.id) {
        await assignToProject.mutateAsync({
          personnelIds: [result.id],
          projectId,
        });
        toast.success(`${firstName} ${lastName} added and assigned to project`);
      } else {
        toast.success(`${firstName} ${lastName} added successfully`);
      }

      resetForm();
      onOpenChange(false);
      onSuccess?.();
    } catch (error) {
      // Error handled by mutation
    }
  };

  return (
    <Dialog open={open} onOpenChange={(isOpen) => {
      if (!isOpen) resetForm();
      onOpenChange(isOpen);
    }}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <UserPlus className="h-5 w-5" />
            Quick Add Personnel
          </DialogTitle>
        </DialogHeader>
        
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-2">
              <Label htmlFor="firstName">First Name *</Label>
              <Input
                id="firstName"
                value={firstName}
                onChange={(e) => setFirstName(e.target.value)}
                placeholder="John"
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="lastName">Last Name *</Label>
              <Input
                id="lastName"
                value={lastName}
                onChange={(e) => setLastName(e.target.value)}
                placeholder="Doe"
                required
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="email">Email *</Label>
            <Input
              id="email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="john.doe@example.com"
              required
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="phone">Phone</Label>
            <Input
              id="phone"
              type="tel"
              value={phone}
              onChange={(e) => setPhone(e.target.value)}
              placeholder="(555) 123-4567"
            />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-2">
              <Label htmlFor="hourlyRate">Hourly Rate *</Label>
              <div className="relative">
                <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">$</span>
                <Input
                  id="hourlyRate"
                  type="number"
                  step="0.01"
                  min="0"
                  value={hourlyRate}
                  onChange={(e) => setHourlyRate(e.target.value)}
                  placeholder="25.00"
                  className="pl-7"
                  required
                />
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="status">Status</Label>
              <Select value={status} onValueChange={(v: "active" | "inactive") => setStatus(v)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="active">Active</SelectItem>
                  <SelectItem value="inactive">Inactive</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          {projectId && (
            <div 
              className="flex items-center gap-2 p-3 rounded-lg bg-secondary/50 cursor-pointer"
              onClick={() => setAutoAssign(!autoAssign)}
            >
              <span
                className={`flex h-5 w-5 items-center justify-center rounded border transition-colors ${
                  autoAssign
                    ? "border-primary bg-primary text-primary-foreground"
                    : "border-muted-foreground/40"
                }`}
              >
                {autoAssign && <Check className="h-3 w-3" />}
              </span>
              <span className="text-sm">
                Auto-assign to: <span className="font-medium">{projectName || "Selected Project"}</span>
              </span>
            </div>
          )}

          <div className="flex justify-end gap-2 pt-2">
            <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
              Cancel
            </Button>
            <Button 
              type="submit" 
              disabled={addPersonnel.isPending || assignToProject.isPending}
            >
              {addPersonnel.isPending || assignToProject.isPending ? "Adding..." : "Add Personnel"}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
}
