-- Pre-configure Jaime Garcia's dashboard with spreadsheet theme
INSERT INTO public.dashboard_configurations (user_id, layout, widgets, theme)
VALUES (
  '5501b08d-ad06-4b99-89aa-1cacf9866b87',
  '{"columns": 4, "widgets": [{"widgetId": "welcome", "position": {"row": 0, "col": 0}, "size": {"width": 4, "height": 1}}, {"widgetId": "revenue-stat", "position": {"row": 1, "col": 0}, "size": {"width": 1, "height": 1}}, {"widgetId": "projects-stat", "position": {"row": 1, "col": 1}, "size": {"width": 1, "height": 1}}, {"widgetId": "staffing-stat", "position": {"row": 1, "col": 2}, "size": {"width": 1, "height": 1}}, {"widgetId": "pending-invoices-stat", "position": {"row": 1, "col": 3}, "size": {"width": 1, "height": 1}}, {"widgetId": "projects-pie-chart", "position": {"row": 2, "col": 0}, "size": {"width": 2, "height": 2}}, {"widgetId": "recent-activity", "position": {"row": 2, "col": 2}, "size": {"width": 2, "height": 2}}, {"widgetId": "quick-actions", "position": {"row": 4, "col": 0}, "size": {"width": 2, "height": 1}}, {"widgetId": "assignments", "position": {"row": 4, "col": 2}, "size": {"width": 2, "height": 1}}]}'::jsonb,
  '[{"id": "welcome", "type": "welcome", "title": "Welcome", "config": {}, "visible": true}, {"id": "revenue-stat", "type": "stat", "title": "Revenue", "config": {"dataSource": "invoices", "metric": "revenue"}, "visible": true}, {"id": "projects-stat", "type": "stat", "title": "Active Projects", "config": {"dataSource": "projects", "metric": "active_count"}, "visible": true}, {"id": "staffing-stat", "type": "stat", "title": "Staff on Site", "config": {"dataSource": "personnel", "metric": "on_site"}, "visible": true}, {"id": "pending-invoices-stat", "type": "stat", "title": "Pending Invoices", "config": {"dataSource": "invoices", "metric": "pending"}, "visible": true}, {"id": "projects-pie-chart", "type": "chart", "title": "Projects by Status", "config": {"dataSource": "projects", "displayOptions": {"chartType": "pie"}}, "visible": true}, {"id": "recent-activity", "type": "activity", "title": "Recent Activity", "config": {"displayOptions": {"limit": 10}}, "visible": true}, {"id": "quick-actions", "type": "quick-actions", "title": "Quick Actions", "config": {}, "visible": true}, {"id": "assignments", "type": "assignments", "title": "My Assignments", "config": {}, "visible": true}]'::jsonb,
  '{"fontSize": "small", "spacing": "compact", "borderRadius": "none", "density": "spreadsheet", "cardOpacity": 100}'::jsonb
)
ON CONFLICT (user_id) DO UPDATE SET
  theme = '{"fontSize": "small", "spacing": "compact", "borderRadius": "none", "density": "spreadsheet", "cardOpacity": 100}'::jsonb,
  updated_at = now();